### ISSUE TITLE
Error resolving merged descriptor properties and parameters

### ISSUE THREAD

**Issue by I816674** [cloudfoundry-incubator/multiapps-controller#370]
Hello,

A new error happened in our latest pipeline when executing the piper function deployToCloudFoundry, what it is surprising is that the same pipeline for the same code was just working fine yesterday without such error
Here is the detailed log:

#2.0#2018 12 13 07:55:45.974#Z#DEBUG#com.sap.cloud.lm.sl.xs2.27361600.MAIN_LOG.processDescriptorTask#
######com.sap.cloud.lm.sl.cf.persistence.services.ProcessLogger########flowable-async-job-executor-thread-2###
[XS2ProcessDescriptorStep] Resolving properties and parameters in merged descriptor...#

#2.0#2018 12 13 07:55:45.989#Z#ERROR#com.sap.cloud.lm.sl.xs2.27361600.MAIN_LOG.processDescriptorTask#
######com.sap.cloud.lm.sl.cf.persistence.services.ProcessLogger########flowable-async-job-executor-thread-2###
[XS2ProcessDescriptorStep] Error resolving merged descriptor properties and parameters: Could not create a valid route from "{route=ui5-flexibility-design-and-configuration-int-integration-green.cfapps.sap.hana.ondemand.com}"#

#2.0#2018 12 13 07:55:45.992#Z#ERROR#com.sap.cloud.lm.sl.xs2.27361600.MAIN_LOG.processDescriptorTask#
######com.sap.cloud.lm.sl.cf.persistence.services.ProcessLogger########flowable-async-job-executor-thread-2###
Exception caught#

com.sap.cloud.lm.sl.common.SLException: Could not create a valid route from "{route=ui5-flexibility-design-and-configuration-int-integration-green.cfapps.sap.hana.ondemand.com}"
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.RouteValidator.attemptToCorrect(RouteValidator.java:24)
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.RouteValidator.attemptToCorrect(RouteValidator.java:13)
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.ParameterValidator.attemptToCorrect(ParameterValidator.java:21)
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.ParametersValidatorHelper.attemptToCorrect(ParametersValidatorHelper.java:96)
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.ParametersValidatorHelper.validateAndCorrect(ParametersValidatorHelper.java:82)
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.ParametersValidatorHelper.lambda$correctInvalidPluralParameters$0(ParametersValidatorHelper.java:70)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.ParametersValidatorHelper.correctInvalidPluralParameters(ParametersValidatorHelper.java:72)
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.ParametersValidatorHelper.validate(ParametersValidatorHelper.java:36)
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.ParametersValidator.validateParameters(ParametersValidator.java:28)
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.v2.ModuleParametersValidator.validate(ModuleParametersValidator.java:17)
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.v2.ModuleParametersValidator.validate(ModuleParametersValidator.java:8)
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.v1.DescriptorParametersValidator.validate(DescriptorParametersValidator.java:63)
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.v1.DescriptorParametersValidator.validateModules(DescriptorParametersValidator.java:57)
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.v2.DescriptorParametersValidator.validate(DescriptorParametersValidator.java:31)
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.v2.DescriptorParametersValidator.validate(DescriptorParametersValidator.java:25)
	at com.sap.cloud.lm.sl.cf.core.validators.parameters.v2.DescriptorParametersValidator.validate(DescriptorParametersValidator.java:11)
	at com.sap.cloud.lm.sl.cf.core.helpers.MtaDescriptorPropertiesResolver.resolve(MtaDescriptorPropertiesResolver.java:80)
	at com.sap.cloud.lm.sl.cf.process.steps.ProcessDescriptorStep.executeStep(ProcessDescriptorStep.java:71)
	at com.sap.cloud.lm.sl.xs2.process.steps.XS2ProcessDescriptorStep.executeStep(XS2ProcessDescriptorStep.java:31)
	at com.sap.cloud.lm.sl.cf.process.steps.SyncFlowableStep.execute(SyncFlowableStep.java:53)
	at org.flowable.engine.impl.delegate.invocation.JavaDelegateInvocation.invoke(JavaDelegateInvocation.java:35)
	at org.flowable.engine.impl.delegate.invocation.DelegateInvocation.proceed(DelegateInvocation.java:35)
	at org.flowable.engine.impl.delegate.invocation.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:26)
	at org.flowable.engine.impl.bpmn.behavior.ServiceTaskDelegateExpressionActivityBehavior.execute(ServiceTaskDelegateExpressionActivityBehavior.java:105)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:258)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:155)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:112)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:76)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:88)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:72)
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:56)
	at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:25)
	at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53)
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:71)
	at org.flowable.common.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:49)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.flowable.common.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:46)
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.job.service.impl.asyncexecutor.ExecuteAsyncRunnable.executeJob(ExecuteAsyncRunnable.java:128)
	at org.flowable.job.service.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:116)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:836)

**Comment by valentinEmpy** [comment]
Hi,
As this is quite an old issue, I assume it is now irrelevant.
Please, in case I am wrong, re-open it for further assistance.
